export const ordersData = [
  {
    key: "1",
    name: "Al-Amin",
    email: "shimizuker@cybereas..",
    extraEmails: "+20",
    avatar: null,
    totalItem: "05",
    location: "Portland, Illinois",
    date: "November 28, 2015",
    status: "pending",
  },
  {
    key: "2",
    name: "Al-Amin",
    email: "nathan.roberts@example.com",
    avatar: null,
    totalItem: "05",
    location: "Pasadena, Oklahoma",
    date: "November 7, 2017",
    status: "pending",
  },
  {
    key: "3",
    name: "Al-Amin",
    email: "debra.holt@example.com",
    avatar: null,
    totalItem: "05",
    location: "Corona, Michigan",
    date: "February 9, 2015",
    status: "pending",
  },
  {
    key: "4",
    name: "Al-Amin",
    email: "nevaeh.simmons@example.com",
    avatar: null,
    totalItem: "05",
    location: "Lafayette, California",
    date: "September 9, 2013",
    status: "pending",
  },
  {
    key: "5",
    name: "Al-Amin",
    email: "tanya.hill@example.com",
    avatar: null,
    totalItem: "05",
    location: "Great Falls, Maryland",
    date: "March 8, 2018",
    status: "pending",
  },
  {
    key: "6",
    name: "Al-Amin",
    email: "tim.jennings@example.com",
    avatar: null,
    totalItem: "05",
    location: "Stockton, New Hampshire",
    date: "December 29, 2012",
    status: "pending",
  },
  {
    key: "7",
    name: "Al-Amin",
    email: "jackson.graham@example.com",
    avatar: null,
    totalItem: "05",
    location: "Syracuse, Connecticut",
    date: "October 31, 2017",
    status: "pending",
  },
];
