
export const SargentData = [
  {
    key: "1",
    name: "Al-Amin",
    email: "shimizuker@cybereas..",
    extraEmails: "+20",
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
    location: "Portland, Illinois",
    date: "November 28, 2015",
  },
  {
    key: "2",
    name: "Al-Amin",
    email: "nathan.roberts@example.com",
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    location: "Pasadena, Oklahoma",
    date: "November 7, 2017",
  },
  {
    key: "3",
    name: "Al-Amin",
    email: "debra.holt@example.com",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    location: "Corona, Michigan",
    date: "February 9, 2015",
  },
  {
    key: "4",
    name: "Al-Amin",
    email: "nevaeh.simmons@example.com",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    location: "Lafayette, California",
    date: "September 9, 2013",
  },
  {
    key: "5",
    name: "Al-Amin",
    email: "tanya.hill@example.com",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    location: "Great Falls, Maryland",
    date: "March 6, 2018",
  },
  {
    key: "6",
    name: "Al-Amin",
    email: "tim.jennings@example.com",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    location: "Stockton, New Hampshire",
    date: "December 29, 2012",
  },
  {
    key: "7",
    name: "Al-Amin",
    email: "jackson.graham@example.com",
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
    location: "Syracuse, Connecticut",
    date: "October 31, 2017",
  },
];
